@url_dev=http://localhost:3052/v1/api

### signup
# @name login
POST {{url_dev}}/shop/signup
Content-Type: application/json
X-API-KEY: xxx000

{
    "name" : "Shop Dev",
    "email" : "vinh9411@vgamestd.com",
    "password" : "abc123"
}
